import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'app/whynot_app.dart';
import 'app/whynot_theme.dart';
import 'firebase_options.dart';

/// Local Firebase project used by the Emulator Suite.
///
/// These values are only used while running the Flutter web application in
/// debug mode. They do not point to the production WhyNot Firebase project.
const FirebaseOptions _localFirebaseOptions = FirebaseOptions(
  apiKey: 'demo-api-key',
  appId: 'demo-app-id',
  messagingSenderId: 'demo-sender-id',
  projectId: 'demo-whynot',
  authDomain: 'demo-whynot.firebaseapp.com',
);

/// Initializes Firebase and starts the WhyNot application.
///
/// While developing on Chrome in debug mode, the application uses the local
/// Firebase Emulator Suite with the `demo-whynot` project.
///
/// Production and non-web builds continue using the Firebase configuration
/// generated by FlutterFire for the real WhyNot project.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final useLocalEmulators = kDebugMode && kIsWeb;

  if (useLocalEmulators) {
    // Use the same project ID as the local Firebase Emulator Suite.
    await Firebase.initializeApp(
      options: _localFirebaseOptions,
    );

    // Authentication stays entirely inside the local emulator.
    await FirebaseAuth.instance.useAuthEmulator(
      '127.0.0.1',
      9099,
    );

    // Firestore reads and writes stay inside the local emulator.
    FirebaseFirestore.instance.useFirestoreEmulator(
      '127.0.0.1',
      8080,
    );

    // Callable Cloud Functions are executed by the local Functions emulator.
    FirebaseFunctions.instanceFor(
      region: 'us-central1',
    ).useFunctionsEmulator(
      '127.0.0.1',
      5001,
    );
  } else {
    // Normal application configuration used outside local Chrome development.
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }

  WhyNotTheme.configureSystemUi();

  runApp(const WhyNotApp());
}